import type { Config } from "tailwindcss";

// Design tokens repris tel quel des maquettes validées
// (frontend/docs/mockups.html) — thème Material Design 3 custom, dark mode.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e1e0ff",
        "on-secondary-fixed-variant": "#3c475a",
        "on-secondary-container": "#aeb9d0",
        "on-error": "#690005",
        "on-secondary": "#263143",
        "surface-variant": "#2d3449",
        "bg-base": "#020617",
        "surface-card": "#0F172A",
        "tertiary-container": "#8083ff",
        "on-surface-variant": "#c2c6d6",
        primary: "#adc6ff",
        "on-primary-fixed": "#001a42",
        "on-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "inverse-surface": "#dae2fd",
        surface: "#0b1326",
        "secondary-container": "#3e495d",
        "on-background": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "primary-container": "#4d8eff",
        "surface-elevated": "#1E293B",
        "on-tertiary-fixed": "#07006c",
        error: "#ffb4ab",
        "on-primary-container": "#00285d",
        "on-tertiary-container": "#0d0096",
        "surface-dim": "#0b1326",
        "on-primary-fixed-variant": "#004395",
        "surface-container-low": "#131b2e",
        "secondary-fixed": "#d8e3fb",
        "tertiary-fixed-dim": "#c0c1ff",
        tertiary: "#c0c1ff",
        "status-done": "#10B981",
        "status-failed": "#F97316",
        "status-processing": "#3B82F6",
        outline: "#8c909f",
        "error-container": "#93000a",
        "outline-variant": "#424754",
        "surface-bright": "#31394d",
        "primary-fixed-dim": "#adc6ff",
        "status-pending": "#64748B",
        "on-secondary-fixed": "#111c2d",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "surface-container-highest": "#2d3449",
        secondary: "#bcc7de",
        "surface-container-high": "#222a3d",
        "on-tertiary": "#1000a9",
        "waveform-stroke": "#1E293B",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-primary": "#002e6a",
        "surface-container": "#171f33",
        "secondary-fixed-dim": "#bcc7de",
        background: "#0b1326",
        "inverse-primary": "#005ac2",
        "surface-tint": "#adc6ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "stack-lg": "32px",
        margin: "40px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-md": ["var(--font-ibm-plex-sans)", "IBM Plex Sans", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        code: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "label-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-ibm-plex-sans)", "IBM Plex Sans", "sans-serif"],
        "headline-sm": ["var(--font-ibm-plex-sans)", "IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
      },
    },
  },
};

export default config;
